all: 
  vars:
    ansible_user: root
    ansible_port: port_number
    ansible_python_interpreter: /usr/bin/python3
  children: 
    single-node:
      host:
        template_name: ansible_host: ip_number
    
    
          
